# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/maven?view=vsts
# https://github.com/acm-jjahn/carts/blob/master/Jenkinsfile
#TAG = "$(DOCKER_REGISTRY_URL):5000/library/$(ARTEFACT_ID)"
# https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/powershell?view=vsts
# http://mohamedradwan.com/2018/03/11/vsts-build-variables-and-echo/
# Write-Host "##vso[task.setvariable variable=YourVSTSVariableName]$yourPowershellVariable"


#'azureSubscriptionEndpoint' input is the name of Azure Service Connection. 
# See Azure Resource Manager service connection to manually set up the connection. 
#'dockerRegistryEndpoint' input is the name of Docker Registry service connection.

#resources:
#  containers:
#  - container: my_container
#    image: ubuntu:16.04

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  APP_NAME: "catalogue"
  VERSION: "1"
  ARTEFACT_ID: "sockshop/$(APP_NAME)"
  DOCKER_REGISTRY: "$(dockerRegistryEndpoint)"
  SUBSCRIPTION_ENDPOINT: "InnovationLab-Dev"
  TAG: "$(DOCKER_REGISTRY)/$(ARTEFACT_ID)"
  TAG_DEV: "$(TAG)-$(VERSION)-$(build.buildId)"
  TAG_STAGING: "$(TAG)-$(VERSION)"

#container: my_container
#  displayName: 'Stage Go Files'
#   displayName: 'Glide Install'
#   displayName: 'Run Go Build'

steps:
- task: CmdLine@2
  inputs:
    displayName: 'Print Environment Info'
    script: printenv

- script: |
    echo '##vso[task.setvariable variable=GOPATH]$(System.DefaultWorkingDirectory)'
    echo 1 GOPATH=$Env:$GOPATH
    echo 2 GOPATH=$GOPATH
    echo 3 GOPATH=$(GOPATH)
    mkdir -p src/github.com/dynatrace-sockshop/catalogue/
    cp -R ./api src/github.com/dynatrace-sockshop/catalogue/
    cp -R ./main.go src/github.com/dynatrace-sockshop/catalogue/
    cp -R ./glide.* src/github.com/dynatrace-sockshop/catalogue/
    cd src/github.com/dynatrace-sockshop/catalogue
    pwd
    ls -l

- task: CmdLine@2
  inputs:
    displayName: 'glide install'
    script: |
      sudo mkdir -p /home/vsts/go/src
      sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
      sudo apt-get install glide

- task: CmdLine@2
  inputs:
    displayName: 'Install packages and dependencies'
    script: |
      glide install
    
- script: |
    go build -a -ldflags -linkmode=external -installsuffix cgo -o $(System.DefaultWorkingDirectory)/catalogue main.go

- task: Docker@1
  displayName: 'Build an image'
  inputs:
    imageName: $(TAG_DEV)

- task: Docker@1
  displayName: Login
  inputs:
    azureSubscriptionEndpoint: $(SUBSCRIPTION_ENDPOINT)
    azureContainerRegistry: $(DOCKER_REGISTRY)
    command: login

- task: Docker@1
  displayName: 'Push an image'
  inputs:
    azureSubscriptionEndpoint: $(SUBSCRIPTION_ENDPOINT)
    azureContainerRegistry: $(DOCKER_REGISTRY)
    command: 'push'
    imageName: $(TAG_DEV)

- task: CopyFiles@2
  inputs:
    contents: manifest/*
    targetFolder: $(Build.ArtifactStagingDirectory)

- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.ArtifactStagingDirectory)
    artifactName: Yaml